export const SIGNIN_STRINGS = {
  brandName: 'ProcurePilot',
  title: 'Sign in to your workspace',
  subtitle: 'Enter your work email and password to access your procurement dashboard.',
  emailLabel: 'Email Address',
  emailPlaceholder: 'you@company.com',
  emailRequired: 'Email is required',
  emailInvalid: 'Please enter a valid email address',
  passwordLabel: 'Password',
  passwordPlaceholder: 'Enter your password',
  passwordRequired: 'Password is required',
  forgotPassword: 'Forgot password?',
  submitButton: 'Sign In',
  submittingButton: 'Signing in...',
  noAccountPrompt: 'Have a platform invitation token?',
  createWorkspaceLink: 'Create workspace',
  // Deliberate security rule: failed sign-in must not reveal whether the account exists
  invalidCredentialsError: 'Invalid email or password.',
  rateLimitedError: 'Too many sign-in attempts. Please wait a few moments and try again.',
  genericError: 'Unable to sign in. Please check your connection and try again.',
  traceIdLabel: 'Reference ID',
} as const;
