export const SHELL_STRINGS = {
  brandName: 'ProcurePilot',
  appTagline: 'Procurement Intelligence',
  toggleNav: 'Toggle navigation',
  navSectionMain: 'Main Navigation',
  navHome: 'Overview',
  navQuotations: 'Quotation Inbox',
  navCompare: 'Smart Compare',
  navSavings: 'Savings Ledger',
  navTeam: 'Team Management',
  navSettings: 'Settings',
  comingSoon: 'Coming Soon',
  switchWorkspace: 'Switch workspace',
  workspaceListTitle: 'Your Workspaces',
  activeBadge: 'Active',
  switchingWorkspace: 'Switching...',
  accountMenuLabel: 'Account options',
  rolePrefix: 'Role:',
  roleOwner: 'Owner',
  roleBuyer: 'Buyer',
  roleBranchManager: 'Branch Manager',
  roleApprover: 'Approver',
  roleViewer: 'Viewer',
  mfaEnabledBadge: 'MFA Active',
  signOut: 'Sign out',
} as const;
