export const SIGNUP_STRINGS = {
  brandName: 'ProcurePilot',
  title: 'Create your workspace',
  subtitle: 'Enter your platform invitation token and business details to set up your isolated workspace.',
  tokenLabel: 'Platform Invitation Token',
  tokenPlaceholder: 'e.g. 32-character invitation token',
  tokenHint: 'Requires a valid 32+ character platform invitation token',
  tokenRequired: 'Invitation token is required',
  tokenMinLength: 'Token must be at least 32 characters',
  businessNameLabel: 'Business Name',
  businessNamePlaceholder: 'Acme Supplies Ltd',
  businessNameRequired: 'Business name is required',
  businessNameMaxLength: 'Business name cannot exceed 200 characters',
  emailLabel: 'Work Email Address',
  emailPlaceholder: 'owner@example.com',
  emailRequired: 'Email is required',
  emailInvalid: 'Please enter a valid email address',
  passwordLabel: 'Password',
  passwordPlaceholder: 'Enter a secure password',
  passwordHint: 'Must be at least 12 characters',
  passwordRequired: 'Password is required',
  passwordMinLength: 'Password must be at least 12 characters',
  regionLabel: 'Operating Region',
  regionPlaceholder: 'Select region...',
  regionRequired: 'Region selection is required',
  currencyLabel: 'Primary Currency',
  currencyPlaceholder: 'Select currency...',
  currencyRequired: 'Primary currency is required',
  taxModelLabel: 'Tax Model',
  taxModelPlaceholder: 'Select tax model...',
  taxModelRequired: 'Tax model is required',
  submitButton: 'Create Workspace & Sign In',
  submittingButton: 'Creating Workspace...',
  alreadyHaveAccount: 'Already have a workspace?',
  signInLink: 'Sign in',
  loadingConfig: 'Loading reference options...',
  configError: 'Unable to load configuration options. Please refresh the page.',
  invitationGatedNotice: 'Workspace creation is invitation-gated during the pilot programme.',
  invitationForbiddenTitle: 'Platform Invitation Refused',
  invitationForbiddenMessage: 'The provided invitation token is missing, expired, spent, or revoked. Workspace creation requires a valid platform invitation.',
  defaultErrorTitle: 'Workspace Creation Failed',
  traceIdLabel: 'Reference ID',
} as const;
